// Expo's ambient types (CSS and asset imports). expo-env.d.ts declares the same
// but is generated by `expo start` and git-ignored, so a fresh checkout (CI) lacks it.
/// <reference types="expo/types" />
