/*
 * The header buttons' icons: the house icons as images (assets/header-icons, generated by
 * `pnpm --filter @agora/web icons:tabs`), for the native `Stack.Toolbar.Button` — liquid glass,
 * `variant="prominent"` for the screen's main action. The native toolbar only takes SF Symbols or
 * images, and only its own buttons as direct children: use it as
 *   <Stack.Toolbar.Button icon={headerIcon.check} iconRenderingMode="template" accessibilityLabel={…} />
 * Never a label in a header: an icon, and its label for VoiceOver.
 */
export const headerIcon = {
  check: require("../../assets/header-icons/check.png"),
  close: require("../../assets/header-icons/close.png"),
  plus: require("../../assets/header-icons/plus.png"),
  refresh: require("../../assets/header-icons/refresh.png"),
  sliders: require("../../assets/header-icons/sliders.png"),
  userPlus: require("../../assets/header-icons/user-plus.png"),
  chevronLeft: require("../../assets/header-icons/chevron-left.png"),
};
